In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [5]:
x,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=42)

In [10]:
from sklearn.linear_model import LogisticRegression

In [12]:
logi = LogisticRegression()
logi.fit(x_train,y_train)

LogisticRegression()

In [13]:
y_pred = logi.predict(x_test)
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1
 1 1 1 0]


In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [17]:
score = accuracy_score(y_test,y_pred)*100
print(score)

cm = confusion_matrix(y_test,y_pred)
print(cm)

84.66666666666667
[[118  17]
 [ 29 136]]


In [21]:
x

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]])

In [26]:
logi.predict([[0.96479937,-0.06644898,0.98676805,0.98676805,0.98676805, 0.98676805,-1.2101605,-0.62807677,1.22727382,1.22727382]])

array([0])

### HYPERPARAMETER TUNING AND CROSS VALIDATION

In [37]:
logi = LogisticRegression()
penalty = ['l1','l2','elasticnet']
c_values = [100,10,1.0,0.1,0.01]
solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky','sag', 'saga']

In [60]:
parmas = dict(penalty=penalty,C= c_values,solver=solver)

In [61]:
# GridSearchCV

In [62]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedGroupKFold
cv = StratifiedGroupKFold()

In [63]:

grid = GridSearchCV(estimator=logi,param_grid=parmas,scoring='accuracy',cv=cv,n_jobs=-1)

In [64]:
grid

GridSearchCV(cv=StratifiedGroupKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [65]:
grid.fit(x_train,y_train)

TypeError: iteration over a 0-d array

In [66]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, StratifiedKFold

# Example: Create dummy data
X = np.random.rand(100, 10)  # 100 samples, 10 features
y = np.random.randint(0, 2, size=100)  # Binary target variable

# Check shapes of X and y
print("X shape:", X.shape)  # Should be (n_samples, n_features)
print("y shape:", y.shape)  # Should be (n_samples,)

# Initialize the logistic regression model
logi = LogisticRegression(max_iter=1000)  # Ensure convergence

# Define the hyperparameters to search
penalties = ['l1', 'l2', 'elasticnet']
c_values = [100, 10, 1.0, 0.1, 0.01]
solvers = ['liblinear', 'saga']  # Include 'saga' for elasticnet

# Create a parameter grid (note: scoring is not included here)
params = {
    'penalty': penalties,
    'C': c_values,
    'solver': solvers
}

# Setup stratified k-fold cross-validation (use StratifiedKFold if not using groups)
cv = StratifiedKFold(n_splits=5)

# Initialize GridSearchCV (move scoring out of param_grid)
grid = GridSearchCV(
    estimator=logi,
    param_grid=params,
    scoring='accuracy',  # Set scoring directly
    cv=cv,
    n_jobs=-1,
    refit=True  # Optionally refit the model with the best parameters
)

# Fit the grid search
grid.fit(X, y)

# To access the best parameters and the best estimator
best_params = grid.best_params_
best_estimator = grid.best_estimator_

print("Best parameters:", best_params)
print("Best estimator:", best_estimator)


X shape: (100, 10)
y shape: (100,)
Best parameters: {'C': 1.0, 'penalty': 'l2', 'solver': 'liblinear'}
Best estimator: LogisticRegression(max_iter=1000, solver='liblinear')


C:\Users\Shiva\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
50 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Shiva\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Shiva\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shiva\AppData\Roaming\Python\Python312\site-