In [2]:
import numpy as np

In [3]:
# Creating array

In [4]:
list1 = [1,2,3]
print(list)

<class 'list'>


In [5]:
arr_list = np.array(list1)

In [6]:
arr_list

array([1, 2, 3])

In [7]:
# 2d array

In [8]:
list1 = [1,2,3]
list2 = [4,5,6]

arr_list2 = np.array([[list1,list2]])
print(arr_list2)

[[[1 2 3]
  [4 5 6]]]


In [9]:
print(arr_list2.ndim)

3


In [10]:
# Numpy array attributes

In [11]:
arr1 = np.array ([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print('Shape :',arr1.shape)
print("Size :", arr1.size)
print("Dtype :",arr1.dtype)
print("N_dim :",arr1.ndim)

Shape : (2, 3)
Size : 6
Dtype : int64
N_dim : 2


In [13]:
# HW: create 2 array - 1d and 3D and find its attributes

In [14]:
arr1 = np.array([1,2,3])
print('Shape :',arr1.shape)
print("Size :", arr1.size)
print("Dtype :",arr1.dtype)
print("N_dim :",arr1.ndim)

Shape : (3,)
Size : 3
Dtype : int64
N_dim : 1


In [15]:
arr3 = np.array([[1,2,3],[4,5,6]])
print('Shape :',arr3.shape)
print("Size :", arr3.size)
print("Dtype :",arr3.dtype)
print("N_dim :",arr3.ndim)

Shape : (2, 3)
Size : 6
Dtype : int64
N_dim : 2


In [16]:
# Array initializatin methods

In [17]:
# zero array
zero_arr = np.zeros((4,5))
print(zero_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
# once array
one_array = np.ones((4,5))
print(one_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# full array
full_array = np.full((4,5),7)
print(full_array)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [20]:
# Identity Matrix
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# Empty array
np.empty(2)

array([1.19511842e-311, 0.00000000e+000])

In [22]:
# evenly spaced array
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [23]:
# specific numbers of values equally spaced bw a range 
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [24]:
# random values array - float
r_array = np.random.rand(3,2)
print(r_array)

[[0.67246681 0.26403283]
 [0.88714305 0.18204643]
 [0.47939861 0.82873351]]


In [25]:
# random value array - int
r_arr = np.random.randint(2,8,(3,3))
print(r_arr)

[[4 5 5]
 [4 6 6]
 [2 6 7]]


In [26]:
# array indexing and slicing 

In [28]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [32]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [34]:
print(b[:,2])

[3 7]


In [40]:
b[1,[1,3]]

array([6, 8])