In [1]:
import numpy as np

In [2]:
lst = np.array([1,2,3,4])

In [3]:
lst * 2

array([2, 4, 6, 8])

In [4]:
a = [1,2,4,'shivam']
np.array(a)

array(['1', '2', '4', 'shivam'], dtype='<U21')

In [5]:
b = [[1,2,3,4],[5,6,7,8],[9,10,11,13]]

In [6]:
b

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 13]]

In [7]:
new = np.array([b])

In [8]:
new

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 13]]])

In [9]:
new[0,1,2]

np.int64(7)

In [10]:
np.random.rand(100)

array([0.35676834, 0.01522226, 0.25581703, 0.55105306, 0.85080412,
       0.06825914, 0.14858934, 0.35627137, 0.17241618, 0.36434598,
       0.34758228, 0.55524187, 0.15068341, 0.74289149, 0.76065437,
       0.80155604, 0.93158696, 0.78228699, 0.89421916, 0.31447027,
       0.11687575, 0.09967277, 0.8408442 , 0.33359891, 0.53511585,
       0.20185342, 0.82824419, 0.06730978, 0.47919052, 0.69009321,
       0.86900539, 0.45371621, 0.30385982, 0.72593081, 0.67084364,
       0.02732185, 0.03774195, 0.77662685, 0.0756026 , 0.75646242,
       0.32016455, 0.13966446, 0.94605696, 0.78641977, 0.8859391 ,
       0.49878001, 0.45314334, 0.82847989, 0.15777655, 0.70357657,
       0.04640872, 0.24539868, 0.89429227, 0.40741728, 0.36823491,
       0.6343723 , 0.98671117, 0.51779042, 0.84486269, 0.25129321,
       0.36796214, 0.18907605, 0.3372582 , 0.09847096, 0.08621805,
       0.82838949, 0.17359828, 0.25823756, 0.85389648, 0.85501376,
       0.23827662, 0.97161537, 0.81124195, 0.80285554, 0.43959

In [11]:
num = np.arange(1,11)

In [12]:
type(num)

numpy.ndarray

In [13]:
arr = np.zeros((2,9))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [24]:
x = np.random.randint(0,2,100)
x

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0], dtype=int32)

In [17]:
f1 = np.random.rand(100)
f2 = np.random.rand(100) * 10
f3 = np.random.randint(0,100,100)
np.random.seed(42)


In [19]:
import pandas as pd 

In [20]:
df = pd.DataFrame({"F1":f1,"F2":f2,"F3":f3,"Output":x})

In [21]:
df

F1        F2  F3  Output
0   0.166253  4.283163  27       0
1   0.260875  6.974412  34       1
2   0.193405  5.480789   7       0
3   0.484283  8.684591  29       0
4   0.277189  3.091992  72       0
..       ...       ...  ..     ...
95  0.496715  4.446065  81       1
96  0.624835  4.698673  15       0
97  0.560501  6.123892  57       0
98  0.318866  8.672618  21       1
99  0.865214  3.772433  41       1

[100 rows x 4 columns]

In [39]:
np.random.rand(20) #generate the number between 0 to 1

array([0.45825289, 0.54561679, 0.94146481, 0.38610264, 0.96119056,
       0.90535064, 0.19579113, 0.0693613 , 0.100778  , 0.01822183,
       0.09444296, 0.68300677, 0.07118865, 0.31897563, 0.84487531,
       0.02327194, 0.81446848, 0.28185477, 0.11816483, 0.69673717])

In [40]:
np.random.randn(19) # generate the number bw -3 to 3

array([ 0.89959988,  0.30729952,  0.81286212,  0.62962884, -0.82899501,
       -0.56018104,  0.74729361,  0.61037027, -0.02090159,  0.11732738,
        1.2776649 , -0.59157139,  0.54709738, -0.20219265, -0.2176812 ,
        1.09877685,  0.82541635,  0.81350964,  1.30547881])

In [44]:
np.random.randint(10,29,30) #generate 30 numbers bw 10 to 29 

array([18, 19, 21, 26, 15, 16, 23, 22, 17, 19, 18, 27, 11, 14, 14, 15, 28,
       17, 25, 22, 10, 26, 16, 22, 13, 13, 15, 28, 21, 16], dtype=int32)

In [46]:
# array attributes 

# Attributes are the variables inside a class 
# Methods are the functions inside the class

In [48]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.shape

(3, 3)

In [53]:
arr.min()

np.int64(1)

In [54]:
arr.max()

np.int64(9)

In [55]:
arr.sum()

np.int64(45)

In [66]:
print(arr.sum(0)) # this will sum column wise
print(arr.sum(1)) #this will sum row wise

[12 15 18]
[ 6 15 24]


In [65]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [68]:
int(arr.mean())

5

In [69]:
arr.std()

np.float64(2.581988897471611)

In [72]:
arr.argmax() # this will tell you the index value of the max element

np.int64(8)

In [74]:
arr.argmin() #this will tell you the index value of the min element

np.int64(0)

### Reshaping and resizing

In [76]:
new = np.arange(1,31)

In [77]:
new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [78]:
new.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [81]:
new = new.reshape(5,6)

In [82]:
new

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

### Indexing and slicing 

In [83]:
# Indexing and slicing of vectors 

In [97]:
v = np.array([[1,2,4],[4,5,6],[7,8,9]])

In [100]:
v

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
v[1,0:2]

array([4, 5])

In [110]:
z = np.array([
    [[1,2,4],[4,5,6],[7,8,9]], 
    [[81,52,14],[14,55,46],[77,98,19]]])



In [111]:
z

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[81, 52, 14],
        [14, 55, 46],
        [77, 98, 19]]])

In [113]:
z[1,2,1:]

array([98, 19])

In [114]:
z.shape

(2, 3, 3)

In [115]:
z[0]

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
z[:, 0, 2]

array([ 4, 14])

In [117]:
z[1]

array([[81, 52, 14],
       [14, 55, 46],
       [77, 98, 19]])

In [118]:
z[1,1,1]

np.int64(55)

In [120]:
z[1, :, :].ndim

2

In [131]:
z[0, :, 1]

array([2, 5, 8])

In [132]:
# How to extract the last column from both matrices?

z[:,2,:]

array([[ 7,  8,  9],
       [77, 98, 19]])

In [143]:
# How to get all elements from the first row of each matrix?

z[:,:,2]

array([[ 4,  6,  9],
       [14, 46, 19]])

In [134]:
z

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[81, 52, 14],
        [14, 55, 46],
        [77, 98, 19]]])

In [138]:
z[1, 2, 1]

np.int64(98)

In [144]:
z[1, :, ::-1]

array([[14, 52, 81],
       [46, 55, 14],
       [19, 98, 77]])

In [ ]:
# How to get all diagonal elements (i.e., 1, 5, 9) from the first matrix?



In [145]:
z[:, :, 1:3]

array([[[ 2,  4],
        [ 5,  6],
        [ 8,  9]],

       [[52, 14],
        [55, 46],
        [98, 19]]])

In [147]:
z

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[81, 52, 14],
        [14, 55, 46],
        [77, 98, 19]]])

In [149]:
# How do you replace the middle element of both matrices with 999?

z[:,1,1] = 999

In [156]:
z

array([[[  1,   2,   4],
        [  4, 999,   6],
        [  7,   8,   9]],

       [[ 81,  52,  14],
        [ 14, 999,  46],
        [ 77,  98,  19]]])

In [157]:
z[:, 1, :]

array([[  4, 999,   6],
       [ 14, 999,  46]])

In [158]:
# Extract all elements in the second column from both matrices.

z[:,:,1]



array([[  2, 999,   8],
       [ 52, 999,  98]])

In [155]:
# How do you flatten the entire array z into a 1D array?

z.ravel()

array([  1,   2,   4,   4, 999,   6,   7,   8,   9,  81,  52,  14,  14,
       999,  46,  77,  98,  19])

In [159]:
# How to get a transposed version of the second matrix

In [160]:
# Get the sum of all elements in the first matrix.

z[1,:,:].sum()

np.int64(1400)

In [161]:
z[::-1]

array([[[ 81,  52,  14],
        [ 14, 999,  46],
        [ 77,  98,  19]],

       [[  1,   2,   4],
        [  4, 999,   6],
        [  7,   8,   9]]])

In [163]:
np.diag(z[1])

array([ 81, 999,  19])

In [164]:
z[1].T

array([[ 81,  14,  77],
       [ 52, 999,  98],
       [ 14,  46,  19]])

In [167]:
# boolean indexing 
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr % 2 == 0

In [169]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [170]:
arr = arr[bool_index]

In [171]:
arr

array([12, 14, 16, 18, 20])

## Array Operations
- Arthmetic operations
- Broadcasting
- Deep & Shallow copy 
- Matrix operations
- Advance array manipulation
- Stacking array
- Splitting array

In [181]:
#  Arthmetic operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [182]:
added = a1+a2
added

array([ 7,  9, 11, 13, 15])

In [183]:
a1

array([1, 2, 3, 4, 5])

In [184]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [185]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [186]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [187]:
# Broadcasting

In [189]:
l = [10,20,30,40]
arr = np.array(l)

In [190]:
arr

array([10, 20, 30, 40])

In [ ]:
arr + 10

array([20, 30, 40, 50])

In [193]:
arr = np.append(arr,[6,7,8])

In [194]:
arr

array([10, 20, 30, 40,  6,  7,  8])