In [468]:
import numpy as np

In [469]:
lst = np.array([1,2,3,4])

In [470]:
lst * 2

array([2, 4, 6, 8])

In [471]:
a = [1,2,4,'shivam']
np.array(a)

array(['1', '2', '4', 'shivam'], dtype='<U21')

In [472]:
b = [[1,2,3,4],[5,6,7,8],[9,10,11,13]]

In [473]:
b

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 13]]

In [474]:
new = np.array([b])

In [475]:
new

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 13]]])

In [476]:
new[0,1,2]

np.int64(7)

In [477]:
np.random.rand(100)

array([1.98842404e-01, 7.11341953e-01, 7.90175541e-01, 6.05959975e-01,
       9.26300879e-01, 6.51077026e-01, 9.14959676e-01, 8.50038578e-01,
       4.49450674e-01, 9.54101165e-02, 3.70818252e-01, 6.68841253e-01,
       6.65922357e-01, 5.91297788e-01, 2.74721793e-01, 5.61243426e-01,
       3.82926875e-01, 9.71712095e-01, 8.48913824e-01, 7.21729521e-01,
       2.35984920e-01, 2.56068323e-01, 4.04335895e-02, 7.10662890e-01,
       1.10890821e-01, 4.39336502e-01, 2.01719202e-01, 8.95763596e-01,
       4.75370223e-01, 5.63275572e-01, 6.95516086e-01, 1.39331454e-01,
       6.04417379e-01, 5.39841091e-01, 2.03061225e-01, 9.42853571e-01,
       5.98865466e-01, 6.94784933e-01, 8.80467839e-01, 6.24354048e-01,
       2.95633686e-01, 1.05494260e-01, 4.56534570e-01, 2.18440437e-01,
       4.16509948e-01, 8.83280259e-01, 3.24345021e-01, 1.22087955e-01,
       3.56297838e-01, 9.06828442e-01, 2.72132249e-01, 6.47690121e-01,
       5.20376995e-04, 3.52568856e-01, 3.04781258e-01, 1.64655853e-01,
      

In [478]:
num = np.arange(1,11)

In [479]:
type(num)

numpy.ndarray

In [480]:
arr = np.zeros((2,9))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [481]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [482]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [483]:
x = np.random.randint(0,2,100)
x

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0], dtype=int32)

In [484]:
f1 = np.random.rand(100)
f2 = np.random.rand(100) * 10
f3 = np.random.randint(0,100,100)
np.random.seed(42)


In [485]:
import pandas as pd 

In [486]:
df = pd.DataFrame({"F1":f1,"F2":f2,"F3":f3,"Output":x})

In [487]:
df

F1        F2  F3  Output
0   0.636333  6.382706  57       1
1   0.250462  5.166963  38       1
2   0.589871  6.571113  13       0
3   0.978893  4.356729  94       1
4   0.486742  7.300393   4       0
..       ...       ...  ..     ...
95  0.442352  2.127279  15       0
96  0.239787  9.461945  86       1
97  0.093873  7.812961  56       1
98  0.182866  1.134646  74       0
99  0.934614  9.309291  11       0

[100 rows x 4 columns]

In [488]:
np.random.rand(20) #generate the number between 0 to 1

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914])

In [489]:
np.random.randn(19) # generate the number bw -3 to 3

array([-1.01283112,  0.31424733, -0.90802408, -1.4123037 ,  1.46564877,
       -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,  0.11092259,
       -1.15099358,  0.37569802, -0.60063869, -0.29169375, -0.60170661,
        1.85227818, -0.01349722, -1.05771093,  0.82254491])

In [490]:
np.random.randint(10,29,30) #generate 30 numbers bw 10 to 29 

array([11, 15, 19, 13, 27, 21, 11, 19, 13, 23, 25, 24, 17, 23, 17, 25, 22,
       27, 24, 22, 18, 24, 22, 10, 16, 18, 10, 21, 17, 20], dtype=int32)

In [491]:
# array attributes 

# Attributes are the variables inside a class 
# Methods are the functions inside the class

In [492]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [493]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [494]:
arr.shape

(3, 3)

In [495]:
arr.min()

np.int64(1)

In [496]:
arr.max()

np.int64(9)

In [497]:
arr.sum()

np.int64(45)

In [498]:
print(arr.sum(0)) # this will sum column wise
print(arr.sum(1)) #this will sum row wise

[12 15 18]
[ 6 15 24]


In [499]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [500]:
int(arr.mean())

5

In [501]:
arr.std()

np.float64(2.581988897471611)

In [502]:
arr.argmax() # this will tell you the index value of the max element

np.int64(8)

In [503]:
arr.argmin() #this will tell you the index value of the min element

np.int64(0)

### Reshaping and resizing

In [504]:
new = np.arange(1,31)

In [505]:
new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [506]:
new.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [507]:
new = new.reshape(5,6)

In [508]:
new

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

### Indexing and slicing 

In [509]:
# Indexing and slicing of vectors 

In [510]:
v = np.array([[1,2,4],[4,5,6],[7,8,9]])

In [511]:
v

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [512]:
v[1,0:2]

array([4, 5])

In [513]:
z = np.array([
    [[1,2,4],[4,5,6],[7,8,9]], 
    [[81,52,14],[14,55,46],[77,98,19]]])



In [514]:
z

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[81, 52, 14],
        [14, 55, 46],
        [77, 98, 19]]])

In [515]:
z[1,2,1:]

array([98, 19])

In [516]:
z.shape

(2, 3, 3)

In [517]:
z[0]

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [518]:
z[:, 0, 2]

array([ 4, 14])

In [519]:
z[1]

array([[81, 52, 14],
       [14, 55, 46],
       [77, 98, 19]])

In [520]:
z[1,1,1]

np.int64(55)

In [521]:
z[1, :, :].ndim

2

In [522]:
z[0, :, 1]

array([2, 5, 8])

In [523]:
# How to extract the last column from both matrices?

z[:,2,:]

array([[ 7,  8,  9],
       [77, 98, 19]])

In [524]:
# How to get all elements from the first row of each matrix?

z[:,:,2]

array([[ 4,  6,  9],
       [14, 46, 19]])

In [525]:
z

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[81, 52, 14],
        [14, 55, 46],
        [77, 98, 19]]])

In [526]:
z[1, 2, 1]

np.int64(98)

In [527]:
z[1, :, ::-1]

array([[14, 52, 81],
       [46, 55, 14],
       [19, 98, 77]])

In [528]:
# How to get all diagonal elements (i.e., 1, 5, 9) from the first matrix?



In [529]:
z[:, :, 1:3]

array([[[ 2,  4],
        [ 5,  6],
        [ 8,  9]],

       [[52, 14],
        [55, 46],
        [98, 19]]])

In [530]:
z

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[81, 52, 14],
        [14, 55, 46],
        [77, 98, 19]]])

In [531]:
# How do you replace the middle element of both matrices with 999?

z[:,1,1] = 999

In [532]:
z

array([[[  1,   2,   4],
        [  4, 999,   6],
        [  7,   8,   9]],

       [[ 81,  52,  14],
        [ 14, 999,  46],
        [ 77,  98,  19]]])

In [533]:
z[:, 1, :]

array([[  4, 999,   6],
       [ 14, 999,  46]])

In [534]:
# Extract all elements in the second column from both matrices.

z[:,:,1]



array([[  2, 999,   8],
       [ 52, 999,  98]])

In [535]:
# How do you flatten the entire array z into a 1D array?

z.ravel()

array([  1,   2,   4,   4, 999,   6,   7,   8,   9,  81,  52,  14,  14,
       999,  46,  77,  98,  19])

In [536]:
# How to get a transposed version of the second matrix

In [537]:
# Get the sum of all elements in the first matrix.

z[1,:,:].sum()

np.int64(1400)

In [538]:
z[::-1]

array([[[ 81,  52,  14],
        [ 14, 999,  46],
        [ 77,  98,  19]],

       [[  1,   2,   4],
        [  4, 999,   6],
        [  7,   8,   9]]])

In [539]:
np.diag(z[1])

array([ 81, 999,  19])

In [540]:
z[1].T

array([[ 81,  14,  77],
       [ 52, 999,  98],
       [ 14,  46,  19]])

In [541]:
# boolean indexing 
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [542]:
bool_index = arr % 2 == 0

In [543]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [544]:
arr = arr[bool_index]

In [545]:
arr

array([12, 14, 16, 18, 20])

## Array Operations
- Arthmetic operations
- Broadcasting
- Deep & Shallow copy 
- Matrix operations
- Advance array manipulation
- Stacking array
- Splitting array

In [546]:
#  Arthmetic operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [547]:
added = a1+a2
added

array([ 7,  9, 11, 13, 15])

In [548]:
a1

array([1, 2, 3, 4, 5])

In [549]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [550]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [551]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [552]:
# Broadcasting

In [553]:
l = [10,20,30,40]
arr = np.array(l)

In [554]:
arr

array([10, 20, 30, 40])

In [555]:
arr + 10

array([20, 30, 40, 50])

In [556]:
arr = np.append(arr,[6,7,8])

In [557]:
arr

array([10, 20, 30, 40,  6,  7,  8])

# Broadcasting

In [558]:
l = [1,2,3,4,5,7]
arr = np.array(l)

In [559]:
arr + 10


array([11, 12, 13, 14, 15, 17])

In [560]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 7]])

In [561]:
arr = np.arange(1,26).reshape(5,5)

In [562]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [563]:
arr + 110

array([[111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135]])

In [564]:
arr / 2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5]])

In [565]:
arr * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

### Deep and shallow copy 

In [566]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [567]:
slicee = a[0:5]
slicee

array([1, 2, 3, 4, 5])

In [568]:
slicee =slicee *10

In [569]:
slicee

array([10, 20, 30, 40, 50])

In [570]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [571]:
l = [1,2,3,4,5,6,7,8,9]

In [572]:
a[4:6] * 10

array([50, 60])

In [573]:
# Martix operations

In [574]:
A  = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [575]:
c = np.append(a,b)

In [576]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13])

In [577]:
A @ B

array([[19, 22],
       [43, 50]])

In [578]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [579]:
np.hstack([A,B])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### EXCERCISE

In [580]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
    
])

In [581]:
r = np.sum(s, axis=1)
for i in b:
    if i != 45:
        print("Suduko is not valid")
        break
else:
    print('Suduko is valid row wise')

Suduko is not valid


In [582]:
c = np.sum(s,axis=0)
for i in c:
    if i != 45:
        print('The sukodu is not valid')
        break
else:
    print("Sukudo is valid column wise") 

Sukudo is valid column wise


In [583]:
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [584]:
mat = np.sum(a[])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2849328889.py, line 1)

In [ ]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
s[:3,:3].sum()

np.int64(45)

In [ ]:
s[:3,3:6].sum()

np.int64(45)

In [ ]:
s[:3,6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [ ]:
s[3:6,:3]

array([[8, 5, 9],
       [4, 2, 6],
       [7, 1, 3]])

In [ ]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n= s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Question

In [585]:
#  coloum [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
# get the shape of the matrix
data.shape

(5, 3)

In [ ]:
# find the avg age of students
data[:,0].mean()
np.mean(data[:,0])

np.float64(18.4)

In [ ]:
# extract math marks of all students
maths_marks = data[:,1]
maths_marks

array([85, 92, 76, 65, 90])

In [ ]:
# find the highest science marks 

data[:,2].max()

np.int64(95)

In [ ]:
# get details of the students who scores more than 90 in maths

data[data[:,1]>90]

array([[19, 92, 88]])

In [ ]:
# increase math marks of all students by 5 
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
# find how many students are younder than 19

len(data[data[:,0]<  19])

3

In [ ]:
# calculate the avg marks in each subject column wise mean

np.mean(data[:,1:],axis=0)


array([81.6, 83.2])

In [ ]:
# get data of students who scored at least 80 in both subject

data[(data[:,1]>=80) & (data[:,2]>= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [591]:
# replace all science marks <75 with 0 
data[:,2][data[:,2]<75] =0

In [592]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

#             Thats all in this notebook 