In [1]:
import numpy as np

In [3]:
lst = np.array([1,2,3,4])

In [5]:
lst * 2

array([2, 4, 6, 8])

In [7]:
a = [1,2,4,'shivam']
np.array(a)

array(['1', '2', '4', 'shivam'], dtype='<U21')

In [8]:
b = [[1,2,3,4],[5,6,7,8],[9,10,11,13]]

In [9]:
b

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 13]]

In [16]:
new = np.array([b])

In [20]:
new

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 13]]])

In [26]:
new[0,1,2]

np.int64(7)

In [28]:
np.random.rand(100)

array([0.54987067, 0.48332729, 0.93289866, 0.15537039, 0.0038655 ,
       0.569887  , 0.52767446, 0.02958185, 0.15867176, 0.14816434,
       0.92956608, 0.8286281 , 0.42986863, 0.99451061, 0.66233317,
       0.81189962, 0.8092849 , 0.79395065, 0.45866686, 0.2814388 ,
       0.45900991, 0.37250666, 0.20515747, 0.67626667, 0.5109078 ,
       0.2815697 , 0.95804651, 0.79319343, 0.51568539, 0.69504315,
       0.25335838, 0.35904308, 0.82104266, 0.41815183, 0.48236207,
       0.89817994, 0.23875613, 0.78785904, 0.99692577, 0.53896658,
       0.91020252, 0.39422108, 0.13600907, 0.20189957, 0.86890209,
       0.13942864, 0.48793148, 0.32854292, 0.41280779, 0.96604148,
       0.91704302, 0.07005648, 0.19902145, 0.48367655, 0.54935162,
       0.74239202, 0.22009578, 0.53799815, 0.06972297, 0.62334504,
       0.04802306, 0.96699557, 0.77815865, 0.30805144, 0.02077001,
       0.58853217, 0.64431809, 0.75191536, 0.99828696, 0.36851034,
       0.12450623, 0.01556229, 0.87190072, 0.16949151, 0.86795

In [30]:
num = np.arange(1,11)

In [32]:
type(num)

numpy.ndarray

In [38]:
arr = np.zeros((2,9))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.linspace(1,52,100)

array([ 1.        ,  1.51515152,  2.03030303,  2.54545455,  3.06060606,
        3.57575758,  4.09090909,  4.60606061,  5.12121212,  5.63636364,
        6.15151515,  6.66666667,  7.18181818,  7.6969697 ,  8.21212121,
        8.72727273,  9.24242424,  9.75757576, 10.27272727, 10.78787879,
       11.3030303 , 11.81818182, 12.33333333, 12.84848485, 13.36363636,
       13.87878788, 14.39393939, 14.90909091, 15.42424242, 15.93939394,
       16.45454545, 16.96969697, 17.48484848, 18.        , 18.51515152,
       19.03030303, 19.54545455, 20.06060606, 20.57575758, 21.09090909,
       21.60606061, 22.12121212, 22.63636364, 23.15151515, 23.66666667,
       24.18181818, 24.6969697 , 25.21212121, 25.72727273, 26.24242424,
       26.75757576, 27.27272727, 27.78787879, 28.3030303 , 28.81818182,
       29.33333333, 29.84848485, 30.36363636, 30.87878788, 31.39393939,
       31.90909091, 32.42424242, 32.93939394, 33.45454545, 33.96969697,
       34.48484848, 35.        , 35.51515152, 36.03030303, 36.54

In [48]:
x = np.random.randint(0,2,100)

In [70]:
f1 = np.random.rand(100)
f2 = np.random.rand(100) * 10
f3 = np.random.randint(0,100,100)
np.random.seed(42)


In [71]:
x

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0], dtype=int32)

In [72]:
import pandas as pd 

In [73]:
df = pd.DataFrame({"F1":f1,"F2":f2,"F3":f3,"Output":x})

In [74]:
df

F1        F2  F3  Output
0   0.638187  2.210490  17       1
1   0.449804  3.298653  42       1
2   0.244262  5.143969  83       0
3   0.776256  4.305437  27       0
4   0.219426  1.027482  23       0
..       ...       ...  ..     ...
95  0.279435  4.051888  19       0
96  0.500432  7.744140  69       1
97  0.808418  3.675119  88       1
98  0.488497  2.601887  90       1
99  0.206842  4.133693  12       0

[100 rows x 4 columns]