In [3]:
import numpy as np

In [4]:
lst = np.array([1,2,3,4])

In [5]:
lst * 2

array([2, 4, 6, 8])

In [6]:
a = [1,2,4,'shivam']
np.array(a)

array(['1', '2', '4', 'shivam'], dtype='<U21')

In [7]:
b = [[1,2,3,4],[5,6,7,8],[9,10,11,13]]

In [8]:
b

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 13]]

In [9]:
new = np.array([b])

In [10]:
new

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 13]]])

In [11]:
new[0,1,2]

np.int64(7)

In [12]:
np.random.rand(100)

array([0.30767793, 0.57858916, 0.33085709, 0.72490207, 0.97891658,
       0.29617394, 0.20927805, 0.62983193, 0.13894564, 0.41841195,
       0.76844313, 0.36030451, 0.18142731, 0.38184188, 0.46481532,
       0.07683477, 0.17756583, 0.1825453 , 0.56341426, 0.33464626,
       0.26211619, 0.41302906, 0.29035299, 0.13165582, 0.04409155,
       0.01629512, 0.70200864, 0.99915198, 0.8449683 , 0.51872468,
       0.2435248 , 0.65152012, 0.20938711, 0.85973793, 0.76723424,
       0.36099832, 0.64620731, 0.80438965, 0.8969975 , 0.52331914,
       0.7429653 , 0.63646537, 0.35684018, 0.26385207, 0.34309726,
       0.7258289 , 0.5005309 , 0.09437368, 0.75520089, 0.03365652,
       0.22545608, 0.36662824, 0.42508148, 0.90775827, 0.92559514,
       0.8077593 , 0.44503605, 0.75908046, 0.97700659, 0.97178012,
       0.34118554, 0.11642424, 0.90883531, 0.65999475, 0.0207222 ,
       0.26812144, 0.83614445, 0.97255514, 0.62967249, 0.7956444 ,
       0.34696631, 0.910721  , 0.08349381, 0.21895097, 0.91157

In [13]:
num = np.arange(1,11)

In [14]:
type(num)

numpy.ndarray

In [15]:
arr = np.zeros((2,9))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [18]:
x = np.random.randint(0,2,100)
x

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int32)

In [19]:
f1 = np.random.rand(100)
f2 = np.random.rand(100) * 10
f3 = np.random.randint(0,100,100)
np.random.seed(42)


In [20]:
import pandas as pd 

In [21]:
df = pd.DataFrame({"F1":f1,"F2":f2,"F3":f3,"Output":x})

In [22]:
df

F1        F2  F3  Output
0   0.831673  4.799502  13       1
1   0.224051  8.850536  42       0
2   0.471458  7.567017  76       0
3   0.323692  9.069819  20       1
4   0.059926  1.492929  49       1
..       ...       ...  ..     ...
95  0.149023  2.985390  50       1
96  0.747653  4.102778  38       0
97  0.153239  9.239915  50       1
98  0.096509  4.091919  98       1
99  0.443392  7.955080  24       1

[100 rows x 4 columns]

In [23]:
np.random.rand(20) #generate the number between 0 to 1

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914])

In [24]:
np.random.randn(19) # generate the number bw -3 to 3

array([-1.01283112,  0.31424733, -0.90802408, -1.4123037 ,  1.46564877,
       -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,  0.11092259,
       -1.15099358,  0.37569802, -0.60063869, -0.29169375, -0.60170661,
        1.85227818, -0.01349722, -1.05771093,  0.82254491])

In [25]:
np.random.randint(10,29,30) #generate 30 numbers bw 10 to 29 

array([11, 15, 19, 13, 27, 21, 11, 19, 13, 23, 25, 24, 17, 23, 17, 25, 22,
       27, 24, 22, 18, 24, 22, 10, 16, 18, 10, 21, 17, 20], dtype=int32)

In [26]:
# array attributes 

# Attributes are the variables inside a class 
# Methods are the functions inside the class

In [27]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.shape

(3, 3)

In [30]:
arr.min()

np.int64(1)

In [31]:
arr.max()

np.int64(9)

In [32]:
arr.sum()

np.int64(45)

In [33]:
print(arr.sum(0)) # this will sum column wise
print(arr.sum(1)) #this will sum row wise

[12 15 18]
[ 6 15 24]


In [34]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [35]:
int(arr.mean())

5

In [36]:
arr.std()

np.float64(2.581988897471611)

In [37]:
arr.argmax() # this will tell you the index value of the max element

np.int64(8)

In [38]:
arr.argmin() #this will tell you the index value of the min element

np.int64(0)

### Reshaping and resizing

In [39]:
new = np.arange(1,31)

In [40]:
new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
new.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
new = new.reshape(5,6)

In [43]:
new

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

### Indexing and slicing 

In [44]:
# Indexing and slicing of vectors 

In [45]:
v = np.array([[1,2,4],[4,5,6],[7,8,9]])

In [46]:
v

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
v[1,0:2]

array([4, 5])

In [48]:
z = np.array([
    [[1,2,4],[4,5,6],[7,8,9]], 
    [[81,52,14],[14,55,46],[77,98,19]]])



In [49]:
z

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[81, 52, 14],
        [14, 55, 46],
        [77, 98, 19]]])

In [50]:
z[1,2,1:]

array([98, 19])

In [51]:
z.shape

(2, 3, 3)

In [52]:
z[0]

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
z[:, 0, 2]

array([ 4, 14])

In [54]:
z[1]

array([[81, 52, 14],
       [14, 55, 46],
       [77, 98, 19]])

In [55]:
z[1,1,1]

np.int64(55)

In [56]:
z[1, :, :].ndim

2

In [57]:
z[0, :, 1]

array([2, 5, 8])

In [58]:
# How to extract the last column from both matrices?

z[:,2,:]

array([[ 7,  8,  9],
       [77, 98, 19]])

In [59]:
# How to get all elements from the first row of each matrix?

z[:,:,2]

array([[ 4,  6,  9],
       [14, 46, 19]])

In [60]:
z

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[81, 52, 14],
        [14, 55, 46],
        [77, 98, 19]]])

In [61]:
z[1, 2, 1]

np.int64(98)

In [62]:
z[1, :, ::-1]

array([[14, 52, 81],
       [46, 55, 14],
       [19, 98, 77]])

In [63]:
# How to get all diagonal elements (i.e., 1, 5, 9) from the first matrix?



In [64]:
z[:, :, 1:3]

array([[[ 2,  4],
        [ 5,  6],
        [ 8,  9]],

       [[52, 14],
        [55, 46],
        [98, 19]]])

In [65]:
z

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[81, 52, 14],
        [14, 55, 46],
        [77, 98, 19]]])

In [66]:
# How do you replace the middle element of both matrices with 999?

z[:,1,1] = 999

In [67]:
z

array([[[  1,   2,   4],
        [  4, 999,   6],
        [  7,   8,   9]],

       [[ 81,  52,  14],
        [ 14, 999,  46],
        [ 77,  98,  19]]])

In [68]:
z[:, 1, :]

array([[  4, 999,   6],
       [ 14, 999,  46]])

In [69]:
# Extract all elements in the second column from both matrices.

z[:,:,1]



array([[  2, 999,   8],
       [ 52, 999,  98]])

In [70]:
# How do you flatten the entire array z into a 1D array?

z.ravel()

array([  1,   2,   4,   4, 999,   6,   7,   8,   9,  81,  52,  14,  14,
       999,  46,  77,  98,  19])

In [71]:
# How to get a transposed version of the second matrix

In [72]:
# Get the sum of all elements in the first matrix.

z[1,:,:].sum()

np.int64(1400)

In [73]:
z[::-1]

array([[[ 81,  52,  14],
        [ 14, 999,  46],
        [ 77,  98,  19]],

       [[  1,   2,   4],
        [  4, 999,   6],
        [  7,   8,   9]]])

In [74]:
np.diag(z[1])

array([ 81, 999,  19])

In [75]:
z[1].T

array([[ 81,  14,  77],
       [ 52, 999,  98],
       [ 14,  46,  19]])

In [76]:
# boolean indexing 
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
bool_index = arr % 2 == 0

In [78]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [79]:
arr = arr[bool_index]

In [80]:
arr

array([12, 14, 16, 18, 20])

## Array Operations
- Arthmetic operations
- Broadcasting
- Deep & Shallow copy 
- Matrix operations
- Advance array manipulation
- Stacking array
- Splitting array

In [81]:
#  Arthmetic operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [82]:
added = a1+a2
added

array([ 7,  9, 11, 13, 15])

In [83]:
a1

array([1, 2, 3, 4, 5])

In [84]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [85]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [86]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [87]:
# Broadcasting

In [88]:
l = [10,20,30,40]
arr = np.array(l)

In [89]:
arr

array([10, 20, 30, 40])

In [90]:
arr + 10

array([20, 30, 40, 50])

In [91]:
arr = np.append(arr,[6,7,8])

In [92]:
arr

array([10, 20, 30, 40,  6,  7,  8])

# Broadcasting

In [97]:
l = [1,2,3,4,5,7]
arr = np.array(l)

In [98]:
arr + 10


array([11, 12, 13, 14, 15, 17])

In [99]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 7]])

In [101]:
arr = np.arange(1,26).reshape(5,5)

In [102]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [103]:
arr + 110

array([[111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135]])

In [104]:
arr / 2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5]])

In [105]:
arr * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

### Deep and shallow copy 

In [107]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [110]:
slicee = a[0:5]
slicee

array([1, 2, 3, 4, 5])

In [112]:
slicee =slicee *10

In [113]:
slicee

array([10, 20, 30, 40, 50])