In [1]:
import numpy as np

In [3]:
lst = np.array([1,2,3,4])

In [5]:
lst * 2

array([2, 4, 6, 8])

In [7]:
a = [1,2,4,'shivam']
np.array(a)

array(['1', '2', '4', 'shivam'], dtype='<U21')

In [8]:
b = [[1,2,3,4],[5,6,7,8],[9,10,11,13]]

In [9]:
b

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 13]]

In [16]:
new = np.array([b])

In [20]:
new

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 13]]])

In [26]:
new[0,1,2]

np.int64(7)

In [28]:
np.random.rand(100)

array([0.54987067, 0.48332729, 0.93289866, 0.15537039, 0.0038655 ,
       0.569887  , 0.52767446, 0.02958185, 0.15867176, 0.14816434,
       0.92956608, 0.8286281 , 0.42986863, 0.99451061, 0.66233317,
       0.81189962, 0.8092849 , 0.79395065, 0.45866686, 0.2814388 ,
       0.45900991, 0.37250666, 0.20515747, 0.67626667, 0.5109078 ,
       0.2815697 , 0.95804651, 0.79319343, 0.51568539, 0.69504315,
       0.25335838, 0.35904308, 0.82104266, 0.41815183, 0.48236207,
       0.89817994, 0.23875613, 0.78785904, 0.99692577, 0.53896658,
       0.91020252, 0.39422108, 0.13600907, 0.20189957, 0.86890209,
       0.13942864, 0.48793148, 0.32854292, 0.41280779, 0.96604148,
       0.91704302, 0.07005648, 0.19902145, 0.48367655, 0.54935162,
       0.74239202, 0.22009578, 0.53799815, 0.06972297, 0.62334504,
       0.04802306, 0.96699557, 0.77815865, 0.30805144, 0.02077001,
       0.58853217, 0.64431809, 0.75191536, 0.99828696, 0.36851034,
       0.12450623, 0.01556229, 0.87190072, 0.16949151, 0.86795