In [1]:
import numpy as np

In [2]:
l1 = [20,30,40]
l2 = [50,60,70]

l1+ l2

[20, 30, 40, 50, 60, 70]

In [3]:
np.array([40,50,60])

array([40, 50, 60])

In [5]:
a = np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [10]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
print(a.ndim)
print(b.ndim)

1
2


In [14]:
# shape

print(a.shape)
b.shape

(3,)


(2, 4)

ACCESSING/ CHANGING SPECIFIC ELEMENTS , ROWS, COLUMS

In [16]:
a= np.array([[1,2,3,4,5,6],[312,212,143,454,31,21]])

In [17]:
a

array([[  1,   2,   3,   4,   5,   6],
       [312, 212, 143, 454,  31,  21]])

In [18]:
a[1,3]

np.int64(454)

In [21]:
# get a specific row 

print(a[0])
print(a[1])

[1 2 3 4 5 6]
[312 212 143 454  31  21]


In [22]:
# get a specific column

a[:,1]


array([  2, 212])

In [23]:
# getting a little more fancy [startindex:endindex:stepsize]
print()