In [1]:
import numpy as np

In [2]:
l1 = [20,30,40]
l2 = [50,60,70]

l1+ l2

[20, 30, 40, 50, 60, 70]

In [3]:
np.array([40,50,60])

array([40, 50, 60])

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
print(a.ndim)
print(b.ndim)

1
2


In [9]:
# shape

print(a.shape)
b.shape

(3,)


(2, 4)

ACCESSING/ CHANGING SPECIFIC ELEMENTS , ROWS, COLUMS

In [10]:
a = np.array([[1,2,3,4,5,6],[312,212,143,454,31,21]])

In [11]:
a

array([[  1,   2,   3,   4,   5,   6],
       [312, 212, 143, 454,  31,  21]])

In [12]:
a[1,3]

np.int64(454)

In [13]:
# get a specific row 

print(a[0])
print(a[1])

[1 2 3 4 5 6]
[312 212 143 454  31  21]


In [14]:
# get a specific column

a[:,1]


array([  2, 212])

In [15]:
# getting a little more fancy [startindex:endindex:stepsize]
print(a)

[[  1   2   3   4   5   6]
 [312 212 143 454  31  21]]


In [16]:
a[0,1:6:2]

array([2, 4, 6])

In [17]:
# changing elements from the array
# a[rowno:colno]

a[0,5] = 30

In [18]:
a

array([[  1,   2,   3,   4,   5,  30],
       [312, 212, 143, 454,  31,  21]])

In [19]:
a[1,4:6] = [50,51]

In [20]:
a[:,2] = [56,57]

In [21]:
a

array([[  1,   2,  56,   4,   5,  30],
       [312, 212,  57, 454,  50,  51]])

In [22]:
# 3d example 

b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [23]:
b.ndim

3

In [24]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
b[0,0,1]

b[1,:,2]

array([ 9, 12])

In [26]:
b[1,1,1:3]

array([11, 12])

In [27]:
# replace

b[1,:,2] = [100,102]



In [28]:
b

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8, 100],
        [ 10,  11, 102]]])

In [29]:
# all 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [30]:
np.full((2,2),23, dtype=float)

array([[23., 23.],
       [23., 23.]])

In [31]:
np.full_like(a,60)

array([[60, 60, 60, 60, 60, 60],
       [60, 60, 60, 60, 60, 60]])

In [32]:
# random decimal numbers

d = np.random.rand(4,2,5)

In [33]:
d.ndim

3

In [34]:
np.random.randint(-10,10,size=(4,6))

array([[ 6,  1,  8,  7, -9,  9],
       [-7,  9, -6,  7, -8,  1],
       [ 7, -5, -4,  7,  2,  1],
       [-1,  0,  9,  0, -2,  1]], dtype=int32)

In [35]:
output = np.ones((5,5))

In [36]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
# How do you create a 1D NumPy array with values ranging from 0 to 9?

a = np.array([0,1,2,3,4,5,6,7,8,9])

In [39]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# How do you create a 2D NumPy array with shape (3, 3) filled with random values?

b = np.random.rand(3, 3) 

In [52]:
b

array([[0.10618913, 0.32474689, 0.78866576],
       [0.93356017, 0.96421195, 0.07328697],
       [0.08243189, 0.69413217, 0.2563066 ]])

In [54]:
# How do you find the shape and data type of a NumPy array?

b.shape

(3, 3)

In [55]:
b.ndim

2

In [56]:
b.dtype


dtype('float64')

In [57]:
b.shape

(3, 3)

In [58]:
# How can you reshape a 1D array of size 9 into a 2D array with 3 rows and 3 columns?

c = a.reshape(3,3)


ValueError: cannot reshape array of size 10 into shape (3,3)

In [65]:
# How do you calculate the mean, median, and standard deviation of a NumPy array? 😊

np.mean(a)

np.float64(4.5)

In [61]:
np.median(a)

np.float64(4.5)

In [62]:
np.std(a)

np.float64(2.8722813232690143)

In [66]:
# How do you perform element-wise addition of two NumPy arrays a and b?