In [4]:
import numpy as np

In [5]:
l1 = [20,30,40]
l2 = [50,60,70]

l1+ l2

[20, 30, 40, 50, 60, 70]

In [6]:
np.array([40,50,60])

array([40, 50, 60])

In [7]:
a = np.array([1,2,3])

In [8]:
a

array([1, 2, 3])

In [9]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
print(a.ndim)
print(b.ndim)

1
2


In [12]:
# shape

print(a.shape)
b.shape

(3,)


(2, 4)

ACCESSING/ CHANGING SPECIFIC ELEMENTS , ROWS, COLUMS

In [13]:
a = np.array([[1,2,3,4,5,6],[312,212,143,454,31,21]])

In [14]:
a

array([[  1,   2,   3,   4,   5,   6],
       [312, 212, 143, 454,  31,  21]])

In [15]:
a[1,3]

np.int64(454)

In [16]:
# get a specific row 

print(a[0])
print(a[1])

[1 2 3 4 5 6]
[312 212 143 454  31  21]


In [17]:
# get a specific column

a[:,1]


array([  2, 212])

In [18]:
# getting a little more fancy [startindex:endindex:stepsize]
print(a)

[[  1   2   3   4   5   6]
 [312 212 143 454  31  21]]


In [23]:
a[0,1:6:2]

array([2, 4, 6])

In [24]:
# changing elements from the array
# a[rowno:colno]

a[0,5] = 30

In [25]:
a

array([[  1,   2,   3,   4,   5,  30],
       [312, 212, 143, 454,  31,  21]])

In [28]:
a[1,4:6] = [50,51]

In [34]:
a[:,2] = [56,57]

In [35]:
a

array([[  1,   2,  56,  50,   5,  30],
       [312, 212,  57,  51,  50,  51]])

In [51]:
# 3d example 

b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [52]:
b.ndim

3

In [53]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
b[0,0,1]

b[1,:,2]

np.int64(2)

In [58]:
b[1,1,1:3]

array([11, 12])

In [60]:
# replace

b[1,:,2] = [100,102]



In [61]:
b

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8, 100],
        [ 10,  11, 102]]])

In [62]:
# all 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [65]:
np.full((2,2),23, dtype=float)

array([[23., 23.],
       [23., 23.]])

In [66]:
np.full_like(a,60)

array([[60, 60, 60, 60, 60, 60],
       [60, 60, 60, 60, 60, 60]])

In [71]:
# random decimal numbers

d = np.random.rand(4,2,5)

In [73]:
d.ndim

3

In [79]:
np.random.randint(-10,10,size=(4,6))

array([[ -9,  -5,   7,  -4,   9,   3],
       [  9,  -6,  -1,   6,   1,   9],
       [ -3,  -4,  -3,   9,  -2,   6],
       [  5,   8,  -6,   9, -10,  -3]], dtype=int32)

In [83]:
output = np.ones((5,5))

In [84]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

: 